### PR TITLE
Add ticket purchase and retrieval endpoints to the API

### PR DESCRIPTION
**Pull request by LuchsHub**
What do you think about this? Feel free to deny the request and tell me if you expected me to go in a different direction.

### CODE REVIEW

**Comment by arneallwardt** [comment]
Is there a reason that you return the event in buy_ticket()? And you should fix the linting errors so the pipeline does not fail

**Comment by 53845714nF** [comment]
Würde dann `count` rausnehmen und noch mal die linter laufen lassen.

**Comment by LuchsHub** [comment]
> Is there a reason that you return the event in buy_ticket()? And you should fix the linting errors so the pipeline does not fail

I think it's conventional. I followed the style of previous methods by @53845714nF, which all return some object. In this case, returning the event for which a ticket has been bought seemed reasonable. Doesn't mean you have to use it in the frontend.

**Comment by LuchsHub** [comment]
I've added quantity and purchase_date to the tickets. Admin now counts as "active employee", so the Swagger API works now. Also fixed a Voucher bug where the name attribute didn't show up in the database.

**Comment by LuchsHub** [comment]
This PR now includes the web sockets. I hope this isn't too confusing. 

@arneallwardt The web socket url is simply "/ws". Could you try connecting to that socket in one of your frontend sites and look, if you're receiving messages there? I really hope this simple approach does the trick.

**Comment by arneallwardt** [comment]
I currently get the following error when trying to create a new voucher:

Screenshot 2024-12-28 at 09 50 35


I try to create it using swagger api so it should be working:

Screenshot 2024-12-28 at 09 50 51

**Comment by arneallwardt** [comment]
on it

**Comment by arneallwardt** [comment]
I still have the issue that I can't retrieve my vouchers as a customer as mentioned in #48 Does it work for you guys?

Screenshot 2024-12-28 at 11 49 52

And what do you think about adding a route like /api/v1/tickets/my-tickets but for vouchers? Its not necessary but would be nice to have in my opinion to keep the api uniform

**Comment by LuchsHub** [comment]
This is intended behaviour, because that route allows to check the vouchers of ANY user. So only employees should be allowed to do that.

I am going to introduce a new route for "my-vouchers" soon.

**Pull request merged**
